config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :artists do
    resources :songs, only: [:edit, :new, :create, :destroy, :update]
  end

  patch '/billboard/:id/song/:song_id', to: 'billboardss#add_song_to_billboard', as: "song_to_billboard"
	delete 'remove_billboard_song/:id/:song_id', to: 'billboards#remove_song_from_billboard', as: 'remove_song_from_billboard'
  
  resources :billboards

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :chart, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.order(:name)
  end

  def show
  end

  def new
    @artist = Artist.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy, :add_song_to_billboard, :remove_song_from_billboard]
  before_action :set_song, only: [:add_song_to_billboard, :remove_song_from_billboard]
  
  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to @billboard
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  def add_song_to_billboard
    @billboard.songs << @song
    redirect_to billboard_path(@billboard)
  end

  def remove_song_from_billboard
    Song.find(params[:song_id]).update(billboard_id: nil)
    redirect_to billboard_path(@billboard)
  end

  private
    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def billboard_params
      params.require(:billboard).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def edit
  end

  def new
    @song = Song.new
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to artist_path(@song.artist)
    else
      render :edit
    end
  end

  def destroy
    artist = @song.artist
    @song.destroy
    redirect_to artist_path(artist)
  end

  private
    def set_artist 
      @artist = Artist.find(params[:artist_id])
    end

    def set_song 
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:title, :artist, :chart)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<h1>Artists</h1>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist %></li>
    <%= link_to "View", artist %>
    <%= link_to "Edit", edit_artist_path(artist) %>
    <%= link_to "Delete", artist_path(artist), method: :delete %>
  <% end %>
</ul>
<hr/>
<%= link_to 'Create a new artist', new_artist_path %>
<%= link_to 'Billboards', billboards_path %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<h3>Songs</h3>
  <% @songs.artist.each do |song| %>
    <%= song.title %>
    <%= link_to "Edit", edit_artist_song_path(@artist, song) %>
    <%= link_to "Delete", artist_song_path(@artist, song), method: :delete %>
  <% end %>
<hr />
<%= link_to "Add Song", new_artist_song_path(@artist) %>
<br />
<%= link_to "Back To Artists", artists_path%>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit Billboard' : 'Create Billboard' %></h1>
<hr />
<%= form_for @billboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/billboards/index.html.erb
<h1>Click a Chart To View the top songs!</h1>

<ul>
  <% @billboards.each do |billboard| %>
    <li><%= link_to billboard.name, billboard %></li>
    <%= link_to "View", billboard %>
    <%= link_to "Edit", edit_billboard_path(billboard) %>
    <%= link_to "Delete", billboard_path(billboard), method: :delete %>
  <% end %>
</ul>
<hr/>
<%= link_to 'Create a new chart', new_billboard_path %>
<%= link_to "Artists", artists_path%>

app/views/billboards/show.html.erb
<h1><%= @billboard.name %></h1>
<hr />
<p>What would you like to do?</p>
<br />
<%= link_to 'Edit Billboard', edit_billboard_path(@billboard) %>
<br />
<%= link_to 'Delete Billboard', @billboard, method: :delete %>
<br />
<%= link_to 'Back', billboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopCharts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>